Avoid running SQLAlchemy schema tests with Ingres dialect
ActianCorp/sqlalchemy-ingres pull request #50
Opened 2024-05-09 18:59 UTC by hab6

When running the SQLAlchemy [dialect compliance suite](https://github.com/sqlalchemy/sqlalchemy/tree/main/lib/sqlalchemy/testing/suite), quite a few tests would fail with some form of the following error:

    sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError)
    ('42503', "[42503] [Actian][Actian II ODBC Driver][INGRES]
    CREATE TABLE: You may not create an object owned by 'test_schema'. (328737) (SQLExecDirectW)")
    [SQL:
    CREATE TABLE test_schema.test_table (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        data VARCHAR(50),
        PRIMARY KEY (id) )

The reason for the error is that the suite contains certain tests that attempt to create and drop tables owned under schemas different than the current user.

Ingres does not support this kind of operation except in rare instances where the current user has 

Internal ticket [II-14148](https://actian.atlassian.net/browse/II-14148)

2024-05-10 13:41 UTC, hab6 commented
I am suspicious about the huge jump in skipped tests when setting `supports_schemas = False` in the IngresDialect class.

Result | Without<br>`supports_schemas = False` | With<br>`supports_schemas = False` | Diff
-- | -- | -- | --
Skipped | 334 | 855 | +521

I think it will be important to run the suite with and without the setting and review the 521 tests that are affected to see they are indeed skipped due to the alternate schema issue and not some side effect.

2024-05-10 18:03 UTC, clach04 requested changes
Looks good.

Needs explanation text (that you wrote in the PR ) in the readme.

Minor tweak suggested for quoting.

2024-05-10 18:03 UTC, clach04 commented on README.testsuite.md
> +Please refer to your vendor documentation for the proper syntax to create these namespaces - the database user must have permission to create and drop tables within these schemas. Its perfectly fine
quote these too, makes it more clear whats a quote (and where from) and our notes

2024-05-10 18:03 UTC, clach04 commented on README.testsuite.md
> +The Ingres dialect disables the ability to run tests that use alternate schemas with the setting `supports_schemas = False` in class `IngresDialect`.
This is a good statement, it needs an explanation adding (steal the text from your PR, that text is perfect).

2024-05-10 18:03 UTC, clach04 commented on lib/sqlalchemy_ingres/base.py
> +    supports_schemas = False
Recommend having a comment here, could simple say "see readme.testsuite.md for details"

2024-05-13 15:28 UTC, hab6 commented
@clach04 Thanks for your review. I added text from the PR to the new README and cleaned it up a bit, including your suggestions for making the quoted text distinct that is taken from the SQLAlchemy repository pages.

Please let me know of additional suggestions. Thanks.

2024-05-13 18:16 UTC, clach04 approved these changes

2024-05-14 21:57 UTC, hab6 commented
Focusing solely on the tests in dialect compliance suite class **ComponentReflectionTest**:

Without the flag `supports_schemas = False` in the **IngresDialect** class, all reflection tests fail with this error _(e.g. involving tables)_: **`[INGRES]CREATE TABLE: You may not create an object owned by 'test_schema'.`** Conversely, with the flag present in the **IngresDialect** class, the majority of the tests are skipped, yet many tests now fall into the `PASS` and `FAIL` categories.

**Results of running ComponentReflectionTest class**
IngresDialect class<br>contains flag<br>`supports_schemas = False` | PASSED | FAILED | ERROR | SKIPPED | TOTAL
--|--|--|--|--|--
No | 0 | 0 | 732 | 0 | 732
Yes | 131 | 104 | 0 | 497 | 732

2024-05-14 21:57 UTC, merged